name: First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print a message
              run: echo "Hello, this is the first workflow!"
            
            - name: List files
              run: ls -la
            
            - name: Read file
              run: cat .github/workflows/first.yml