name: Solar System Unit Tests

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'
        # paths:
        #     - 'solar-system/**'

env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js version 18
              uses: actions/setup-node@v5
              with:
                  node-version: '18'

            - name: Install Dependencies
              run: npm install
              working-directory: ./solar-system

            - name: Run Unit Tests
              run: npm test
              working-directory: ./solar-system