name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5
            
            - name: List files in workspace
              run: ls -ltra

            - name: Execute ASCII Generation Script
              run: |
                chmod +x ascii-artwork.sh
                ./ascii-artwork.sh
